plugins {
    id 'com.android.application'
}

android {
    namespace 'studio.alans.fxwatcher'
    compileSdk 34

    defaultConfig {
        applicationId 'studio.alans.fxwatcher'
        minSdk 29
        targetSdk 34
        versionCode 5
        versionName '2.3'
    }

    signingConfigs {
        bridge {
            storeFile file('bridge.keystore')
            storePassword 'camapsbridge'
            keyAlias 'bridge'
            keyPassword 'camapsbridge'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.bridge
        }
        debug {
            signingConfig signingConfigs.bridge
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
